"""Atualização de Tarefa

Revision ID: 65186940b16d
Revises: 4c8e7a478052
Create Date: 2025-11-25 12:59:18.618407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65186940b16d'
down_revision = '4c8e7a478052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('entregue', sa.Boolean(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa_model')
    # ### end Alembic commands ###
